Minor code style improvements
iosphere/ISHMapboxDynamicFontObserver pull request #4
Opened 2017-08-22 13:46 UTC by shagedorn

2017-08-22 13:47 UTC, shagedorn commented on ISHMapboxDynamicFontObserver.m
> +                                                                                                   options:cameraValue.options];
This is more of a guess... I did not know how to build this, so I didn't, could you please give it a try if it compiles? Else I'll revert this line (or only fix the indentation) @felixLam

2017-08-23 09:28 UTC, felixLam requested changes

2017-08-23 09:28 UTC, felixLam commented on ISHMapboxDynamicFontObserver.m
> +                                                                                                   options:cameraValue.options];
`options` is not available https://github.com/mapbox/mapbox-gl-native/blob/ios-v3.6.2/platform/darwin/src/MGLStyleValue.h#L351

2017-08-23 12:59 UTC, shagedorn commented
@felixLam please take another look.

2017-08-23 22:27 UTC, merged